### ISSUE TITLE
Expanding and collapsing subtrees using keyboard

### ISSUE THREAD

**Issue by th** [rochus-keller/CrossLine#9]
Hi,

is there a keyboard shortcut for opening and closing sub-items (2.3 in Welcome example database)?

**Comment by rochus-keller** [comment]
No, there is no such shortcut; why do you think it's necessary?

**Comment by th** [comment]
I often collapse and expand often in my workflow (to get a quick overview). Reaching for the mouse and hitting the small triangle (very small, maybe because HiDPI and Windows is always problematic) feels slow.

**Comment by rochus-keller** [comment]
I have no  hidpi display and no idea what size Crossline and it's icons is actually displayed on such; on which OS are you? I think on Windows you can configure applications to use a kind of compatibility mode which simulates 72 dpi or so.

All my laptops have trackpoint, so I never had an issue with switching to the mouse so far. Since CrossLine remembers open/close state of items I rarely have to click on the triangle. But even if you had a shortcut, you still needed to somehow select the current item, so you would have to use the mouse anyway, isn't it?

All shortcuts so far are optimized for quick data entry.

**Comment by th** [comment]
I'd just use the cursor keys to select items, I guess, but fair enough!
